-- MySQL Script generated by MySQL Workbench
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema enigma-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema enigma-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `enigma-db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `enigma-db` ;

-- -----------------------------------------------------
-- Table `enigma-db`.`coins_pack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enigma-db`.`coins_pack` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` INT NOT NULL,
  `quantity` INT NOT NULL,
  `offer` INT NOT NULL,
  `image` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enigma-db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enigma-db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `fullname` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `hash_password` VARCHAR(64) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `image` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `date_of_birth` DATETIME(6) NOT NULL,
  `country` VARCHAR(3) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `address` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `coins` INT NOT NULL,
  `is_self_banned` TINYINT(1) NOT NULL,
  `self_banned_at` DATETIME NULL DEFAULT NULL,
  `email_confirm` TINYINT(1) NOT NULL,
  `confirmation_token` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `IX_users_email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `IX_users_nickname` (`nickname` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enigma-db`.`friendRequests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enigma-db`.`friendRequests` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `SenderId` INT NOT NULL,
  `ReceiverId` INT NOT NULL,
  `SentAt` DATETIME(6) NOT NULL,
  `Status` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_friendRequests_SenderId` (`SenderId` ASC) VISIBLE,
  CONSTRAINT `FK_friendRequests_users_SenderId`
    FOREIGN KEY (`SenderId`)
    REFERENCES `enigma-db`.`users` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enigma-db`.`game_tables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enigma-db`.`game_tables` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `game_type` INT NOT NULL,
  `max_player` INT NOT NULL,
  `min_player` INT NOT NULL,
  `table_state` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enigma-db`.`game_histories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enigma-db`.`game_histories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `game_table_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `game_type` INT NOT NULL,
  `total_matches_played` INT NOT NULL,
  `total_bet_amount` INT NOT NULL,
  `chip_result` INT NOT NULL,
  `joined_at` DATETIME(6) NOT NULL,
  `left_at` DATETIME(6) NULL DEFAULT NULL,
  `last_match_id_processed` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `IX_game_histories_game_table_id` (`game_table_id` ASC) VISIBLE,
  INDEX `IX_game_histories_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_game_histories_game_tables_game_table_id`
    FOREIGN KEY (`game_table_id`)
    REFERENCES `enigma-db`.`game_tables` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `FK_game_histories_users_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `enigma-db`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enigma-db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enigma-db`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `coins_pack_id` INT NOT NULL,
  `stripe_session_id` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ethereum_transaction_hash` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `is_paid` TINYINT(1) NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `paid_date` DATETIME(6) NOT NULL,
  `price` INT NOT NULL,
  `coins` INT NOT NULL,
  `pay_mode` INT NOT NULL,
  `order_type` INT NOT NULL,
  `ethereum_price` DECIMAL(65,30) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `IX_orders_coins_pack_id` (`coins_pack_id` ASC) VISIBLE,
  INDEX `IX_orders_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_orders_coins_pack_coins_pack_id`
    FOREIGN KEY (`coins_pack_id`)
    REFERENCES `enigma-db`.`coins_pack` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_orders_users_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `enigma-db`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enigma-db`.`user_friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enigma-db`.`user_friends` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `friend_id` INT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `IX_user_friends_user_id_friend_id` (`user_id` ASC, `friend_id` ASC) VISIBLE,
  INDEX `IX_user_friends_friend_id` (`friend_id` ASC) VISIBLE,
  CONSTRAINT `FK_user_friends_users_friend_id`
    FOREIGN KEY (`friend_id`)
    REFERENCES `enigma-db`.`users` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
